<?php
session_start();
include_once("config.php");

?>
<!DOCTYPE html>
<html> 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>View shopping cart</title>
<link href="style/style.css" rel="stylesheet" type="text/css">
<script src='magipay.js' type='text/javascript'></script>

</head>
<body>
<div id="products-wrapper">
 <h1>View Cart</h1>
 <div class="view-cart">
 	<?php
    $current_url = base64_encode($url="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
	if(isset($_SESSION["products"]))
    {
	    $total = 0;
		echo '<form method="post" action="paypal-express-checkout/process.php">';
		echo '<ul>';
		$cart_items = 0;
		foreach ($_SESSION["products"] as $cart_itm)
        {
           $product_code = $cart_itm["code"];
		   $results = $mysqli->query("SELECT product_name,product_desc, price FROM products WHERE product_code='$product_code' LIMIT 1");
		   $obj = $results->fetch_object();
		   
		    echo '<li class="cart-itm">';
			echo '<span class="remove-itm"><a href="cart_update.php?removep='.$cart_itm["code"].'&return_url='.$current_url.'">&times;</a></span>';
			echo '<div class="p-price">'.$currency.$obj->price.'</div>';
            echo '<div class="product-info">';
			echo '<h3>'.$obj->product_name.' (Code :'.$product_code.')</h3> ';
            echo '<div class="p-qty">Qty : '.$cart_itm["qty"].'</div>';
            echo '<div>'.$obj->product_desc.'</div>';
			echo '</div>';
            echo '</li>';
			$subtotal = ($cart_itm["price"]*$cart_itm["qty"]);
			$total = ($total + $subtotal);

			echo '<input type="hidden" name="item_name['.$cart_items.']" value="'.$obj->product_name.'" />';
			echo '<input type="hidden" name="item_code['.$cart_items.']" value="'.$product_code.'" />';
			echo '<input type="hidden" name="item_desc['.$cart_items.']" value="'.$obj->product_desc.'" />';
			echo '<input type="hidden" name="item_qty['.$cart_items.']" value="'.$cart_itm["qty"].'" />';
			$cart_items ++;
			
        }
    	echo '</ul>';
		echo '<span class="check-out-txt">';
		echo '<strong>Total : '.$currency.$total.'</strong>  ';
		echo '</span>';
		//echo '<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Pay with Magi</button>';
		echo '</form>';
		
		
		
    }else{
		echo 'Your Cart is empty';
	}
	
    ?>
    </div>
	
	<?php
		require_once("magipay.class.php"); // REQUIRE THE MAGIPAY CLASS
	
		/** PAYMENT BOX **/
		$options = array(
				"public_key"  => "YOUR MAGIPAY PUBLIC KEY", 	//PUBLIC KEY FOR THE SPECIFIC BOX ID
				"clientID" => "YOUR MAGIPAY CLIENTID",		//YOUR CLIENT ID GENERATED BY M-EPAYS
				"boxID"     => BOX ID, 						//BOX ID GENERATED BY M-EPAYS 
				"invoiceID"     => "INVOICEID", 	//SAMPLE INVOICE ID.	
				"amountUSD"   => $total					//AMOUNT OF INVOICE IN USD. IN THIS EXAMPLE, 
														//THE INVOICE AMOUNT IS REPRESENTED BY THE VARIABLE $total
														// WHICH IS GENERATED BY MERCHANT'S DATABASE. (LINE 42)

		);
		
		// Initialise Payment Class
		$magibox = new magipay ($options);
		
		if($magibox->check_transaction_status()){
			//PLACE YOUR CODE HERE WHEN THE PAYMENT IS RECEIVED
			echo "<script type='text/javascript'>alert('thank you')</script>";
		}

	?>
	
	<?php $magibox->display_magibox() ?>
	
</div>
</body>
</html>
